### ISSUE TITLE
CPLUS_INCLUDE_PATH: unbound variable

### ISSUE THREAD

**Issue by lawrenceleejr** [crogan/RestFrames#1]
Out of the box compilation in rc environment gives this error:

setup.sh: line 4: CPLUS_INCLUDE_PATH: unbound variable
    failed: installation of Ext_RestFrames failed

I've been hacking this locally to change setup.sh to read:

```
export RESTFRAMESSYS=$PWD
export DYLD_LIBRARY_PATH=$RESTFRAMESSYS/lib:$DYLD_LIBRARY_PATH
export LD_LIBRARY_PATH=$RESTFRAMESSYS/lib:$LD_LIBRARY_PATH
export CPLUS_INCLUDE_PATH=$RESTFRAMESSYS/include
```

which of course will break CPLUS_INCLUDE_PATH if you're otherwise using it. Not sure why when asking for $CPLUS_INCLUDE_PATH it doesn't evaluate to "" instead of throwing an error. Thoughts?

-L

**Comment by crogan** [comment]
How did you send me this email through GitHub??? I cc'ed you explicitly
just in case I don't understand how this works.

It does seem weird that CPLUS_INCLUDE_PATH doesn't evaluate to "" by
default. I just pushed a new version of setup.sh that should hopefully fix
this (protecting against an unbound variable)

By-the-way - what exactly gives the error:

## 

setup.sh: line 4: CPLUS_INCLUDE_PATH: unbound variable

## failed: installation of Ext_RestFrames failed

? This is the Ext_RestFrames build calling setup.sh? From what I
understand, using "CPLUS_INCLUDE_PATH" is probably not the best coding
practice... I did this just for running ROOT macros with CINT command line
compiling so it would find the includes, libRestFrames.so etc. For the
Ext_RestFrames
package build the includes and library should probably linked directly at
the compile step using "-I" and "-L" flags, respectively. In general I've
started looking into an autotools solution to the make/install anyway, so
this will likely change at some point (but not so soon maybe?). For now
working in a few environments, the rc one included, is probably sufficient.

Cheers,
Chris

**Comment by lawrenceleejr** [comment]
Yeah. That fix works perfectly and no long needs me to hack it up. Thanks.

And yeah this was happening when Ext_RestFrames was trying to compile RestFrames. Perhaps rc has stricter environment requirements or something. 

(And I'm just submitting an actual issue report on GitHub. Clear way we can track bugs / features / whatever.)
