### ISSUE TITLE
Seg fault when MET = 0

### ISSUE THREAD

**Issue by rsmith54** [crogan/RestFrames#3]
I was running over a truth sample where some events have no true MET.  I don't think anyone else has done this (?).

I was seg faulting on some  events where MET = 0.  

I added a small number to the MET value, and everything finishes fine, so I suspect there is a bug in AnalyzeEvent() when MET = 0 exactly.  I can provide more information to reproduce this if you need.

**Comment by crogan** [comment]
Hi Russel,

Thanks for the heads up. Some more info to reproduce this would be great -
seg faults are bad.

Cheers
Chris

**Comment by kratsg** [comment]
Was this resolved?

**Comment by crogan** [comment]
Yes, this was fixed and committed
