### ISSUE TITLE
Compile error if include before SUSYObjDef_xAOD.h

### ISSUE THREAD

**Issue by max-cw** [crogan/RestFrames#5]
I'm not sure if you're interest, but today I ran into a strange issue. If I include SUSYTools/SUSYObjDef_xAOD.h after the RestFrames' header files, my code won't compile. The error message is like this:

```
In file included from /export/home/max/Stop0L/RootCoreBin/include/RestFrames/RFBase.hh:58:0,
                 from /export/home/max/Stop0L/RootCoreBin/include/RestFrames/RestFrame.hh:33,
                 from /export/home/max/Stop0L/RootCoreBin/include/RestFrames/ReconstructionFrame.hh:33,
                 from /export/home/max/Stop0L/RootCoreBin/include/RestFrames/LabRecoFrame.hh:33,
                 from /export/home/max/Stop0L/Stop0LRun2/Stop0LRun2/RJigsaw.h:4,
                 from /export/home/max/Stop0L/Stop0LRun2/Root/RJigsaw.cxx:1:
/export/home/max/Stop0L/RootCoreBin/include/RestFrames/RFLog.hh:135:17: error: ‘RFLog’ has not been declared
   #define m_End RFLog::EndMessage
```

If I move SUSYObjDef_xAOD.h to before the RestFrames', it's fine.

**Comment by kratsg** [comment]
This sounds like an issue with SUSYTools.

**Comment by rsmith54** [comment]
I just got this error.

I think this is actually because m_End is a macro used by the C++ std.  I think it's probably best to update  RestFrames to use a slightly different macro name.  I just created a pull request which makes this change.

**Comment by crogan** [comment]
Hi Russell,

Interesting - I never realized this was used in c++ STD.  What did you
rename it to? (Changing the name of this to something better was on my ttd
already, just low priority)

Cheers
Chris

**Comment by rsmith54** [comment]
Hey @crogan ,

Just changed it to m_RF_End .

There may be something better, but it seems to fix this issue as far as I can tell.

Cheers,
Russell
